name: firebase_to_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.3

# Dependências do projeto
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
